/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface QuickStarterInterface extends Interface {
    getFunction(nameOrSignature: "campaigns" | "contribute" | "contributions" | "createCampaign" | "nextCampaignId" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignCreated" | "ContributionReceived" | "FundsWithdrawn" | "GoalReached"): EventFragment;

    encodeFunctionData(functionFragment: 'campaigns', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contribute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'contributions', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'createCampaign', values: [string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextCampaignId', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'campaigns', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'contributions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextCampaignId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace CampaignCreatedEvent {
      export type InputTuple = [id: BigNumberish, creator: AddressLike, title: string, goal: BigNumberish, deadline: BigNumberish];
      export type OutputTuple = [id: bigint, creator: string, title: string, goal: bigint, deadline: bigint];
      export interface OutputObject {id: bigint, creator: string, title: string, goal: bigint, deadline: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ContributionReceivedEvent {
      export type InputTuple = [id: BigNumberish, contributor: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, contributor: string, amount: bigint];
      export interface OutputObject {id: bigint, contributor: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundsWithdrawnEvent {
      export type InputTuple = [id: BigNumberish, creator: AddressLike, amount: BigNumberish];
      export type OutputTuple = [id: bigint, creator: string, amount: bigint];
      export interface OutputObject {id: bigint, creator: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GoalReachedEvent {
      export type InputTuple = [id: BigNumberish, totalPledged: BigNumberish];
      export type OutputTuple = [id: bigint, totalPledged: bigint];
      export interface OutputObject {id: bigint, totalPledged: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface QuickStarter extends BaseContract {
    
    connect(runner?: ContractRunner | null): QuickStarter;
    waitForDeployment(): Promise<this>;

    interface: QuickStarterInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    campaigns: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, boolean] & {id: bigint, title: string, creator: string, goal: bigint, pledged: bigint, deadline: bigint, open: boolean }],
      'view'
    >
    

    
    contribute: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    contributions: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    createCampaign: TypedContractMethod<
      [_title: string, _goalInWei: BigNumberish, _deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    nextCampaignId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'campaigns'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, boolean] & {id: bigint, title: string, creator: string, goal: bigint, pledged: bigint, deadline: bigint, open: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'contribute'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'contributions'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'createCampaign'): TypedContractMethod<
      [_title: string, _goalInWei: BigNumberish, _deadline: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextCampaignId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [_campaignId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CampaignCreated'): TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
getEvent(key: 'ContributionReceived'): TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
getEvent(key: 'FundsWithdrawn'): TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
getEvent(key: 'GoalReached'): TypedContractEvent<GoalReachedEvent.InputTuple, GoalReachedEvent.OutputTuple, GoalReachedEvent.OutputObject>;

    filters: {
      
      'CampaignCreated(uint256,address,string,uint256,uint256)': TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
      CampaignCreated: TypedContractEvent<CampaignCreatedEvent.InputTuple, CampaignCreatedEvent.OutputTuple, CampaignCreatedEvent.OutputObject>;
    

      'ContributionReceived(uint256,address,uint256)': TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
      ContributionReceived: TypedContractEvent<ContributionReceivedEvent.InputTuple, ContributionReceivedEvent.OutputTuple, ContributionReceivedEvent.OutputObject>;
    

      'FundsWithdrawn(uint256,address,uint256)': TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
      FundsWithdrawn: TypedContractEvent<FundsWithdrawnEvent.InputTuple, FundsWithdrawnEvent.OutputTuple, FundsWithdrawnEvent.OutputObject>;
    

      'GoalReached(uint256,uint256)': TypedContractEvent<GoalReachedEvent.InputTuple, GoalReachedEvent.OutputTuple, GoalReachedEvent.OutputObject>;
      GoalReached: TypedContractEvent<GoalReachedEvent.InputTuple, GoalReachedEvent.OutputTuple, GoalReachedEvent.OutputObject>;
    
    };
  }